config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get '/search', to: 'pages#search', as: :search
  post '/search', to: 'pages#search'
  post '/marker-info', to: 'pages#marker_info', as: 'marker_info'
  post '/custom-marker', to: 'pages#custom_marker', as: 'custom_marker'
  patch '/custom-marker', to: 'pages#render_overview'
  get '/result/', to: 'pages#result', as: :result
  delete '/markers/:marker_id/favorites', to: 'favorites#destroy'

  resources :favorites, only: %i[index]

  resources :markers, only: %i[new create] do
    resources :reviews, only: %i[new create]
    resources :favorites, only: :create
  end

  resources :reviews, only: %i[index edit update destroy]
  resources :favorites, only: %i[index edit update]
end

app/views/pages/_add_favorites.html.erb
<p class="add" data-controller="add-favorite" data-add-favorite-path-value="<%= path %>"><i class="fa-regular fa-heart fav-icon"></i></p>

app/views/pages/_banner.html.erb
<div class= "hero-banner">

  <div class="container hero-container">
  <div class="row row-login ">
    <% if user_signed_in? %>
      <div class="dropdown d-flex justify-content-end">
        <% if current_user.photo.present? %>
          <img src="<%= current_user.photo %>" class="avatar-btn avatar dropdown-toggle" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup"true" aria-expanded="false"/>
        <% elsif %>
          <img class="avatar drop-down-toggle" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="https://res.cloudinary.com/diiu2j0fw/image/upload/v1654177959/samples/placeholder_b5vap2.png" alt="">
        <% end %>
        <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
          <%= link_to "My profile", edit_user_registration_path, class: "dropdown-item" %>
          <%= link_to "My favorites", favorites_path, class: "dropdown-item" %>
          <%= link_to "My reviews", reviews_path, class: "dropdown-item" %>
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
        </div>
      </div>
    <% else %>
        <div class="d-flex justify-content-end login-div" >
          <%= link_to "Login", new_user_session_path, class: "home-btn" %>
        </div>
    <% end %>
  </div>
  <div class="home row align-items-center justify-content-between">
    <div class="hero-title">
      <h1>Nightskyper</h1>
      <p>Find the perfect place to shoot the stars in the best conditions.</p>
    </div>
    <div class='d-flex justify-content-end'>
      <%= form_with class:'w-50 d-flex text-end align-items-center', url: search_path, method: 'GET' do |f| %>
        <%= f.text_field :query, class: 'form-control searchbar-input', placeholder: 'Explore an area' %>
        <%= f.submit 'Search', name: nil, class:'home-search-btn' %>
      <% end %>
    </div>
  </div>
</div>

app/views/pages/_info_window.html.erb
<div data-controller="new-marker-modal">
  <p><%= marker.title %></p>
  <% if marker.description %>
    <%= link_to 'Show more', result_path(coordinates: [marker.longitude, marker.latitude]) %>
  <% else %>
    <div class="d-flex flex-column">
      <%= link_to 'Show more', result_path(coordinates: [marker.longitude, marker.latitude]) %>
      <%= link_to 'Add this marker', "#", id: "add-marker", data: { turbolinks: false, new_marker_target: "btn" } %>
    </div>
  <% end %>
</div>

app/views/pages/_map.html.erb
<div class="map"
  data-controller="mapbox"
  data-mapbox-search-path-value="<%= search_path %>"
  data-mapbox-marker-info-path-value="<%= marker_info_path %>"
  data-mapbox-custom-marker-path-value="<%= custom_marker_path %>"
  data-mapbox-bounds-value="<%= map_boundaries.to_json %>"
  data-mapbox-api-key-value="<%= key %>">
</div>

app/views/pages/_marker-card.html.erb
<div class="markers d-flex flex-column">
  <div class="marker-container d-flex">
    <% if marker.photo.present? %>
      <div data-controller="popup-img">
        <img class="marker-img popup-img" src="<%= marker.photo %>" data-popup-img-target="img" alt="">
        <div class="modal" data-popup-img-target="modal">
          <!-- The Close Button -->
          <span class="close" data-popup-img-target="close">&times;</span>
          <!-- Modal Image -->
          <img class="modal-content" data-popup-img-target="modalImg">
        </div>
      </div>
    <% else %>
      <div data-controller="popup-img">
        <img class="marker-img popup-img" src="https://images.pexels.com/photos/360912/pexels-photo-360912.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2" alt="" data-popup-img-target="img">
        <div class="modal" data-popup-img-target="modal">
          <!-- The Close Button -->
          <span class="close" data-popup-img-target="close">&times;</span>
          <!-- Modal Image -->
          <img class="modal-content" data-popup-img-target="modalImg">
        </div>
      </div>
    <% end %>
    <div class="marker-card">
      <div class="marker-content">
        <div class="d-flex justify-content-between">
          <h2><%= link_to marker.title, result_path(coordinates: [marker.longitude, marker.latitude]) %></h2>
          <% if current_user && marker.id && !marker.favorite?(current_user) %>
            <%= render '/pages/add_favorites.html.erb', path: path %>
          <% elsif current_user && marker.id && marker.favorite?(current_user) %>
            <%= render '/pages/remove_favorites.html.erb', path: path %>
          <% end %>
        </div>
        <h3><%= marker.description %></h3>
          <div class="marker-bottom">
            <p> <%= marker.address.split(", ")[-6] %> - <%= marker.address.split(", ")[-3] %> - <%= marker.address.split(", ")[-2] %></p>

            <div class= "rating">
              <% marker.average_rating.times do %>
                <span class="fa fa-star checked"></span>
              <% end %>

              <% (5 - marker.average_rating).times do %>
                <span class="fa-solid fa-star unchecked"></span>
              <% end %>
            </div>
          </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/_new_review_form.html.erb
<div class="row d-flex justify-content-center">
  <div class="col-6 w-75">
  <%= simple_form_for([@marker, @review]) do |f| %>
    <%= f.input :rating, collection: (1..5).to_a, label: "Add a rating" %>
    <%= f.input :date, as: :date, html5: true, label: "When did you go to this place ?" %>
    <%= f.input :content, as: :text, label: "Your review:" %>
    <%= f.input :photos, as: :hidden, value: @review.photos, input_html: { data: { controller: 'cloudinary-reviews' } }, class: "cloudinary-button" %>
    <div class="d-flex justify-content-center">
    <%= f.button :submit, class: "NS-button" %>
    </div>
  <% end %>
  </div>
</div>

app/views/pages/_overview.html.erb
<div class="row mx-5 mb-3">
  <div class="col d-flex justify-content-left align-items-center ">
    <div class="my-3">
        <% if Date.parse(day[:datetime]) === Date.today %>
        <h4 data-date="<%= day[:datetime] %>">Today</h4>
        <div><%= day[:datetime] %></div>
        <% elsif Date.parse(day[:datetime]) === Date.tomorrow %>
        <h4>Tomorrow</h4>
        <div>datetime: <%= day[:datetime] %></div>
        <% else %>
        <h4><%= Date::DAYNAMES[Date.parse(day[:datetime]).wday] %></h4>
        <div>datetime: <%= day[:datetime] %></div>
        <% end %>
    </div>
  </div>
  <div class="col d-flex justify-content-center align-items-center text-center">
    <h4><%= place_name %></h4>
  </div>
  <div class="col d-flex justify-content-end align-items-center">
    <p class="p-1 m-0">Long : <%= marker.longitude.round(2) %></p>
    <p class="p-1 m-0">Lat : <%= marker.latitude.round(2) %></p>
  </div>
</div>
<div class="row my-2">
  <div class="col-10 border-bottom m-auto"></div>
</div>
<div class="row my-2">
  <div class="d-flex justify-content-end">
    <% if current_user && marker.id && !marker.favorite?(current_user) %>
      <%= render '/pages/add_favorites.html.erb', path: path %>
    <% elsif current_user && marker.id && marker.favorite?(current_user) %>
      <%= render '/pages/remove_favorites.html.erb', path: path %>
    <% end %>
  </div>
</div>
<div class="row justify-content-around mx-3 mt-3 mb-5">
  <div class="col-3">
    <div class="flip-card text-center">
      <div class="flip-card-inner">
        <div class="flip-card-front p-3">
          <% condition = day[:conditions].split(",")[0]%>
          <div class="my-3">
            <%= image_tag("#{@weather.get_url(condition)}", width: "50%") %>
          </div>
          <%= day[:conditions]%>
          <div class="my-2">
            <h4><%= (((day[:temp].to_i)-32)/1.8).round(1) %>℃</h4>
          </div>
        </div>
        <div class="flip-card-back p-3 text-center">
          <p><strong>Temp.max :</strong> <%= (((day[:tempmax].to_i)-32)/1.8).round(1) %>℃</p>
          <p><strong>Temp.min :</strong> <%= (((day[:tempmin].to_i)-32)/1.8).round(1) %>℃</p>
          <p><strong>Temp :</strong> <%= (((day[:temp].to_i)-32)/1.8).round(1) %>℃</p>
          <p><strong>Humidity :</strong> <%= day[:humidity] %> %</p>
          <p><strong>Cloudcover :</strong> <%= day[:cloudcover] %> %</p>
          <p class="font-italic"><%= day[:description] %></p>
        </div>
      </div>
    </div>
  </div>
  <div class="col-3">
    <div class="flip-card text-center">
      <div class="flip-card-inner">
        <div class="flip-card-front p-3">
          <% phase = day[:moonphase]%>
          <div class="my-3">
            <%= image_tag("#{@weather.get_url(phase)}", width: "50%") %>
          </div>
          <h4><%= "#{@weather.get_moonphase(phase)}" %></h4>
        </div>
        <div class="flip-card-back p-3 text-center">
          <p><strong>Sunrise :</strong> <%= day[:sunrise] %></p>
          <p><strong>Sunset :</strong> <%= day[:sunset] %></p>
          <p>-</p>
          <p><strong>Moonrise :</strong> <%= day[:moonrise] %></p>
          <p><strong>Moonset :</strong> <%= day[:moonset] %></p>
        </div>
      </div>
    </div>
  </div>
  <div class="col-3">
    <div class="flip-card text-center">
      <div class="flip-card-inner">
        <div class="flip-card-front p-3">
          <div class="my-3">
            <%= image_tag("bortle/light-bulb.svg", width: "40%") %>
          </div>
          <h5>Bortle: <%= @bortle %></h5>
        </div>
        <div class="flip-card-back bortle-card p-3">
          <p>Bortle class is a light pollution scale from 0 to 10.</p>
          <p>0 is a pure sky without any light pollution</p>
          <p>10 is a saturated sky by light pollution</p>
          <h6 class="text-center">Bortle: <%= @bortle %></h6>
        </div>
      </div>
    </div>
  </div>
</div>

<% if day == Date.today %>
  <%= link_to "View details", search_path(coordinates: [marker.longitude, marker.latitude]), class:"NS-button" %>
<% end %>

app/views/pages/_prediction-card-duplicate.html.erb
<h2>prediction card</h2>

<div class="cards d-flex flex-column ">
  <% meteo_prediction.each do |jour| %>
    <div class="card mb-4 box-shadow">
      <div class="card-body">
        <div class="text-center mb-3">
          <% if Date.parse(jour[:datetime]) === Date.today %>
          <h4>Today</h4>
          <div>datetime: <%= jour[:datetime] %></div>
          <% elsif Date.parse(jour[:datetime]) === Date.tomorrow %>
           <h4>Tomorrow</h4>
          <div>datetime: <%= jour[:datetime] %></div>
          <% else %>
          <h4><%= Date::DAYNAMES[Date.parse(jour[:datetime]).wday] %></h4>
          <div>datetime: <%= jour[:datetime] %></div>
          <% end %>
        </div>
        <div class="row">
          <div class="col-4">
            <div>tempmax: <%= (((jour[:tempmax].to_i)-32)/1.8).round(1) %>℃</div>
            <div>tempmin: <%= (((jour[:tempmin].to_i)-32)/1.8).round(1) %>℃</div>
            <div>temp: <%= (((jour[:temp].to_i)-32)/1.8).round(1) %>℃</div>
            <div>humidity: <%= jour[:humidity] %> %</div>
            <div>cloudcover: <%= jour[:cloudcover] %> %</div>
          </div>
          <div class="col-4">
            <div>sunrise: <%= jour[:sunrise] %></div>
            <div>sunset: <%= jour[:sunset] %></div>
            <div>moonphase: <%= jour[:moonphase] %></div>
            <div>moonrise: <%= jour[:moonrise] %></div>
            <div>moonset: <%= jour[:moonset] %></div>
          </div>
          <div class="col-4">
            <div>conditions: <%= jour[:conditions] %></div>
            <div>description: <%= jour[:description] %></div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/pages/_remove_favorites.html.erb
<p class="remove" data-controller="remove-favorite" data-remove-favorite-path-value="<%= path %>"><i class="fa-solid fa-heart fav-icon"></i></a>

app/views/pages/_review-card.html.erb
<div class="review-container">
  <div class="review-username">
    <% if review.user.photo.present? %>
      <img src="<%= review.user.photo %>" class="review-avatar"/>
    <% else %>
      <img class="review-avatar" src="https://upload.wikimedia.org/wikipedia/commons/7/7c/Profile_avatar_placeholder_large.png" alt="">
    <% end %>
    <h2><%= review.user.username %></h2>
  </div>
  <div class="review-content">

      <div class="review-top d-flex justify-content-between">
        <h3><%= review.date %></h3>
        <p class="rating text-end">
          <% review.rating.times do %>
            <span class="fa fa-star checked"></span>
          <% end %>
          <% (5 - review.rating).times do %>
            <span class="fa-solid fa-star unchecked"></span>
          <% end %>
        </p>
      </div>
      <p class="review-text"><%= review.content %></p>
    <div class="review-underline"></div>
    <div class="review-images d-flex align-items-center">
      <% review.photos&.split(',')&.each do |photo| %>
        <div data-controller="popup-img">
          <img src="<%= photo %>" class="review-image popup-img" data-popup-img-target="img"/>
          <div class="modal" data-popup-img-target="modal">
            <!-- The Close Button -->
            <span class="close" data-popup-img-target="close">&times;</span>
            <!-- Modal Image -->
            <img class="modal-content" data-popup-img-target="modalImg">
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<% @dnone %>

<%= render 'banner' %>

app/views/pages/result-duplicate.html.erb
<div class="row">
  <div class="result-container my-5" data-controller="result">
    <% @meteo_prediction.first(7).each_with_index do |day, index| %>
      <div class="day-<%= index %>">
        <div class="overview-result pt-3" style="display:none;" data-result-target="overview<%= index %> overviews">
          <%= render 'overview', day: day, marker: @marker, place_name: @place_name, bortle: @bortle, path: marker_favorites_path(@marker) %>
        </div>
        <div class="prediction-result collapse multiCollapse" data-result-target="prediction<%= index %> predictions" data-action="click->result#toggleOverviewPrediction">
          <%= render 'prediction-card', day: day %>
        </div>
      </div>
    <% end %>
    <div class="d-flex justify-content-center" data-action="click->result#checkForCollapse">
      <button class="btn btn-light btn-forecast" type="button" data-bs-toggle="collapse" data-bs-target=".multiCollapse" aria-expanded="false" aria-controls="multiCollapseExample">Forecasts</button>
    </div>
  </div>
</div>

<div class="row">
  <div class="reviews">
      <% if @marker  %>
        <div class="review-title d-flex justify-content-between">
          <h2> Reviews</h2>
          <%= link_to 'Add a review', new_marker_review_path(@marker), class: "NS-button" %>
        </div>
        <div class="title-line review-line"></div>
        <% @marker.reviews.each do |review|%>
          <%= render 'review-card', review: review %>
        <% end %>
      <% else %>
        <p> No marker</p>
      <% end %>
  </div>
</div>

app/views/pages/result.html.erb
<div class="row">
  <div class="result-container my-5" data-controller="result">
    <% if @meteo_prediction %>
      <% @meteo_prediction.first(7).each_with_index do |day, index| %>
        <div class="day-<%= index %>">
          <div class="overview-result pt-3" style="display:none;" data-result-target="overview<%= index %> overviews">
            <%= render 'overview', day: day, marker: @marker, place_name: @place_name, bortle: @bortle, path: @path %>
          </div>
          <div class="prediction-result collapse multiCollapse" data-result-target="prediction<%= index %> predictions" data-action="click->result#toggleOverviewPrediction">
            <%= render 'prediction-card', day: day %>
          </div>
        </div>
      <% end %>
      <div class="d-flex justify-content-center" data-action="click->result#checkForCollapse">
        <button class="btn btn-light btn-forecast" type="button" data-bs-toggle="collapse" data-bs-target=".multiCollapse" aria-expanded="false" aria-controls="multiCollapseExample">Forecasts</button>
      </div>
    <% else %>
      <h3>Weather conditions are unavailable at the moment. Please try again later.</h3>
    <% end %>
  </div>
</div>

<% if @marker.id  %>
  <div class="row">
    <div class="reviews">
      <div class="review-title d-flex justify-content-between">
        <h2> Reviews</h2>
          <button class="NS-button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal" id="butt">
            Add a Review
          </button>
      </div>
      <div class="title-line review-line"></div>
      <% @marker.reviews.each do |review|%>
        <%= render 'review-card', review: review %>
      <% end %>
    </div>
  </div>

  <!-- Modal -->
  <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="form modal-content">
        <div class=" form-header d-flex justify-content-end">
          <button type="button" class="btn-close pt-2 pe-2" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body pt-0">
          <%= render "new_review_form" %>
        </div>
      </div>
    </div>
  </div>

  <script>
    document.getElementById("butt").addEventListener("click", test)
    function test () {
      const backdrop = document.querySelectorAll(".modal-backdrop")
      backdrop[0].remove()
    }
  </script>
<% end %>

app/views/pages/search.html.erb
<div id="overview" class="my-5">
  <% if @meteo_prediction.present? %>
    <%= render 'overview', day: @meteo_prediction.first, marker: @marker, place_name: @place_name, bortle: @bortle %>
  <% end %>
</div>

<div class="d-flex justify-content-between">

  <div class="cards cards-container">

    <div id="marker-cards" class="cards">
      <% @markers&.each do |marker| %>
        <%= render 'marker-card', marker: marker, path: marker_favorites_path(marker) %>
      <% end %>
    </div>
  </div>

  <div class="map-container">
    <%=
      render 'map',
      search_path: search_path,
      marker_info_path: marker_info_path,
      map_boundaries: @map_boundaries,
      key: ENV['MAPBOX_API_KEY'] %>
  </div>
</div>